EMPTY = 1
FRIENDLY = 2
ENEMY = 3
CONTESTED = 4
FRIENDLY_UNIT = 5
ENEMY_UNIT = 6

# 1 unit types
UNIT_TYPE_ONE = 21
UNIT_TYPE_TWO = 22
UNIT_TYPE_THREE = 23
UNIT_TYPE_FOUR = 24

UNIT_TYPES = [UNIT_TYPE_ONE, UNIT_TYPE_ONE, UNIT_TYPE_ONE, UNIT_TYPE_ONE, UNIT_TYPE_TWO, UNIT_TYPE_TWO, UNIT_TYPE_TWO, UNIT_TYPE_TWO, 
				UNIT_TYPE_THREE, UNIT_TYPE_THREE, UNIT_TYPE_THREE, UNIT_TYPE_FOUR, UNIT_TYPE_FOUR, UNIT_TYPE_FOUR, UNIT_TYPE_FOUR, UNIT_TYPE_TWO]

from .app import App
